# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191205_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cells_visibility',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
